package report

import (
	"fmt"
	"log"
	"strings"

	"github.com/go-pdf/fpdf"
)

// sanitizeText transliterates common UTF-8 punctuation and strips unsupported non-ASCII characters
// to prevent gofpdf from rendering garbled bytes or panicking in the final PDF.
func sanitizeText(s string) string {
	s = strings.ReplaceAll(s, "“", "\"")
	s = strings.ReplaceAll(s, "”", "\"")
	s = strings.ReplaceAll(s, "‘", "'")
	s = strings.ReplaceAll(s, "’", "'")
	s = strings.ReplaceAll(s, "—", "-")
	s = strings.ReplaceAll(s, "–", "-")

	var b strings.Builder
	for _, r := range s {
		// gofpdf strictly needs ISO-8859-1. We force it to ASCII 0-127 for maximum safety.
		if r <= 127 {
			b.WriteRune(r)
		}
	}
	return b.String()
}

// SafePDF wraps gofpdf to automatically sanitize all text inputs.
type SafePDF struct {
	*fpdf.Fpdf
}

func (p *SafePDF) SCell(w, h float64, txtStr string) {
	p.Fpdf.Cell(w, h, sanitizeText(txtStr))
}

func (p *SafePDF) SMultiCell(w, h float64, txtStr, borderStr, alignStr string, fill bool) {
	p.Fpdf.MultiCell(w, h, sanitizeText(txtStr), borderStr, alignStr, fill)
}

func (p *SafePDF) SCellFormat(w, h float64, txtStr, borderStr string, ln int, alignStr string, fill bool, link int, linkStr string) {
	p.Fpdf.CellFormat(w, h, sanitizeText(txtStr), borderStr, ln, alignStr, fill, link, linkStr)
}

// GeneratePDFReport creates a formatted, easy-to-digest PDF report from the structured data.
func GeneratePDFReport(data *ReportData) error {
	basePdf := fpdf.New("P", "mm", "A4", "")
	pdf := &SafePDF{basePdf}
	pdf.SetTitle(sanitizeText(fmt.Sprintf("OSINT Report for %s", data.Domain)), false)

	// --- Cover Page ---
	pdf.AddPage()
	pdf.SetFont("Arial", "B", 24)
	pdf.Ln(40)
	pdf.SCellFormat(0, 15, "Cyber Threat Intelligence", "", 1, "C", false, 0, "")
	pdf.SCellFormat(0, 15, "Domain Analysis Report", "", 1, "C", false, 0, "")
	
	pdf.Ln(20)
	pdf.SetFont("Arial", "B", 18)
	pdf.SetTextColor(0, 51, 102) // Dark Blue
	pdf.SCellFormat(0, 10, data.Domain, "", 1, "C", false, 0, "")
	
	pdf.Ln(20)
	pdf.SetTextColor(0, 0, 0)
	pdf.SetFont("Arial", "", 12)
	pdf.SCellFormat(0, 10, fmt.Sprintf("Scan Date: %s", data.ScanTimestamp.Format("2006-01-02 15:04:05 UTC")), "", 1, "C", false, 0, "")
	pdf.SCellFormat(0, 10, "Generated by gomain_analysis", "", 1, "C", false, 0, "")

	// --- Page Footer Setup ---
	pdf.SetFooterFunc(func() {
		pdf.SetY(-15)
		pdf.SetFont("Arial", "I", 8)
		pdf.SetTextColor(128, 128, 128)
		pdf.SCellFormat(0, 10, fmt.Sprintf("Page %d", pdf.PageNo()), "", 0, "C", false, 0, "")
	})

	// --- Executive Summary / WHOIS ---
	pdf.AddPage()
	addSectionHeader(pdf, "1. Domain Registration (WHOIS)")
	pdf.SetFont("Courier", "", 9)
	pdf.SMultiCell(0, 5, data.WHOIS, "", "", false)
	pdf.Ln(10)

	// --- DNS & Infrastructure ---
	addSectionHeader(pdf, "2. Infrastructure & DNS")
	pdf.SetFont("Arial", "B", 10)
	pdf.SCell(0, 8, "A / AAAA / MX Records:")
	pdf.Ln(8)
	pdf.SetFont("Arial", "", 10)
	if len(data.DNSRecords) > 0 {
		for _, record := range data.DNSRecords {
			pdf.SCell(0, 6, "• " + record)
			pdf.Ln(6)
		}
	} else {
		pdf.SCell(0, 6, "No DNS records found.")
		pdf.Ln(6)
	}
	pdf.Ln(5)

	pdf.SetFont("Arial", "B", 10)
	pdf.SCell(0, 8, "Reverse DNS Lookup:")
	pdf.Ln(8)
	pdf.SetFont("Arial", "", 10)
	if len(data.ReverseDNS) > 0 {
		for ip, domains := range data.ReverseDNS {
			pdf.SCell(0, 6, fmt.Sprintf("• %s -> %s", ip, strings.Join(domains, ", ")))
			pdf.Ln(6)
		}
	} else {
		pdf.SCell(0, 6, "No reverse DNS information found.")
		pdf.Ln(6)
	}
	pdf.Ln(10)

	// --- Geolocation ---
	addSectionHeader(pdf, "3. Geolocation")
	if len(data.Geolocation) > 0 {
		for _, geo := range data.Geolocation {
			pdf.SetFont("Arial", "B", 10)
			pdf.SCell(0, 8, fmt.Sprintf("IP: %s", geo.IP))
			pdf.Ln(6)
			pdf.SetFont("Arial", "", 10)
			pdf.SCell(0, 6, fmt.Sprintf("Location: %s, %s, %s (%s)", geo.City, geo.Region, geo.Country, geo.CountryCode))
			pdf.Ln(6)
			pdf.SCell(0, 6, fmt.Sprintf("Coordinates: %.4f, %.4f | Timezone: %s", geo.Latitude, geo.Longitude, geo.Timezone))
			pdf.Ln(10)
		}
	} else {
		pdf.SetFont("Arial", "", 10)
		pdf.SCell(0, 6, "No geolocation data available.")
		pdf.Ln(10)
	}

	// --- SSL/TLS Certificates ---
	pdf.AddPage()
	addSectionHeader(pdf, "4. SSL/TLS Certificates")
	if len(data.Certificates) > 0 {
		for i, cert := range data.Certificates {
			pdf.SetFont("Arial", "B", 10)
			pdf.SetFillColor(240, 240, 240)
			title := fmt.Sprintf("Certificate #%d [%s]", i+1, cert.Source)
			if cert.ID != 0 {
				title += fmt.Sprintf(" (ID: %d)", cert.ID)
			}
			pdf.SCellFormat(0, 8, title, "1", 1, "L", true, 0, "")
			
			pdf.SetFont("Arial", "", 9)
			pdf.SCellFormat(30, 6, "Subject:", "L", 0, "L", false, 0, "")
			pdf.SMultiCell(0, 6, cert.Subject, "R", "L", false)
			
			pdf.SCellFormat(30, 6, "Issuer:", "L", 0, "L", false, 0, "")
			pdf.SMultiCell(0, 6, cert.Issuer, "R", "L", false)
			
			pdf.SCellFormat(30, 6, "Validity:", "L", 0, "L", false, 0, "")
			pdf.SCellFormat(0, 6, fmt.Sprintf("%s  TO  %s", cert.ValidFrom.Format("2006-01-02"), cert.ValidTo.Format("2006-01-02")), "R", 1, "L", false, 0, "")
			
			pdf.SCellFormat(30, 6, "SANs:", "LB", 0, "L", false, 0, "")
			sans := strings.Join(cert.DNSNames, ", ")
			if len(sans) > 100 {
				sans = sans[:97] + "..."
			}
			pdf.SMultiCell(0, 6, sans, "RB", "L", false)
			pdf.Ln(4)
		}
	} else {
		pdf.SetFont("Arial", "", 10)
		pdf.SCell(0, 6, "No certificate information available.")
		pdf.Ln(10)
	}

	// --- Web Content Analysis ---
	pdf.AddPage()
	addSectionHeader(pdf, "5. Web Content Analysis")
	if data.WebAnalysis != nil {
		pdf.SetFont("Arial", "B", 10)
		pdf.SCell(0, 6, fmt.Sprintf("Title: %s", data.WebAnalysis.Title))
		pdf.Ln(8)
		
		pdf.SetFont("Arial", "", 10)
		if len(data.WebAnalysis.Emails) > 0 {
			pdf.SCell(0, 6, "Emails: " + strings.Join(data.WebAnalysis.Emails, ", "))
			pdf.Ln(6)
		}
		if len(data.WebAnalysis.Technologies) > 0 {
			pdf.SCell(0, 6, "Technologies: " + strings.Join(data.WebAnalysis.Technologies, ", "))
			pdf.Ln(6)
		}
		
		pdf.Ln(4)
		pdf.SetFont("Arial", "B", 10)
		pdf.SCell(0, 6, fmt.Sprintf("Links Discovered (%d total)", len(data.WebAnalysis.Links)))
		pdf.Ln(6)
		pdf.SetFont("Arial", "", 9)
		pdf.SetTextColor(0, 0, 255)
		
		// Only print up to 30 links to save space
		linkCount := len(data.WebAnalysis.Links)
		displayLimit := 30
		if linkCount < displayLimit {
			displayLimit = linkCount
		}
		for i := 0; i < displayLimit; i++ {
			link := data.WebAnalysis.Links[i]
			if len(link) > 90 {
				link = link[:87] + "..."
			}
			pdf.SCellFormat(0, 5, link, "", 1, "L", false, 0, "")
		}
		pdf.SetTextColor(0, 0, 0)
		if linkCount > displayLimit {
			pdf.Ln(2)
			pdf.SCellFormat(0, 5, fmt.Sprintf("... and %d more links (omitted for brevity)", linkCount - displayLimit), "", 1, "I", false, 0, "")
		}
		pdf.Ln(10)
	} else {
		pdf.SetFont("Arial", "", 10)
		pdf.SCell(0, 6, "No web content analyzed.")
		pdf.Ln(10)
	}

	// --- Threat Intelligence & Reputation ---
	pdf.AddPage()
	addSectionHeader(pdf, "6. Threat Intelligence & Reputation")
	
	pdf.SetFont("Arial", "B", 11)
	pdf.SCell(0, 8, "VirusTotal Community Scoring:")
	pdf.Ln(8)
	pdf.SetFont("Arial", "", 10)
	if data.MaliciousScore > 0 {
		pdf.SetTextColor(200, 0, 0) // Red warning
		pdf.SCell(0, 6, fmt.Sprintf("WARNING: Domain flagged as malicious by %d security vendors.", data.MaliciousScore))
		pdf.Ln(6)
	} else if data.VT_Tags != nil {
		pdf.SetTextColor(0, 128, 0) // Green
		pdf.SCell(0, 6, "Clean: 0 malicious vendor detections.")
		pdf.Ln(6)
	} else {
		pdf.SetTextColor(128, 128, 128)
		pdf.SCell(0, 6, "VirusTotal check skipped (VT_API_KEY absent).")
		pdf.Ln(6)
	}
	
	pdf.SetTextColor(0,0,0)
	if len(data.VT_Tags) > 0 {
		pdf.SCell(0, 6, "Domain Tags: " + strings.Join(data.VT_Tags, ", "))
		pdf.Ln(6)
	}
	pdf.Ln(5)

	pdf.SetFont("Arial", "B", 11)
	pdf.SCell(0, 8, "Identity & Credential Breaches (HaveIBeenPwned):")
	pdf.Ln(8)
	pdf.SetFont("Arial", "", 10)
	if len(data.BreachedEmails) > 0 {
		for email, breaches := range data.BreachedEmails {
			pdf.SetTextColor(200, 0, 0) // Red
			pdf.SCell(0, 6, "[COMPROMISED] " + email)
			pdf.Ln(6)
			pdf.SetTextColor(0, 0, 0)
			pdf.SCell(0, 6, "Found in breaches: " + strings.Join(breaches, ", "))
			pdf.Ln(8)
		}
	} else if data.WebAnalysis != nil && len(data.WebAnalysis.Emails) > 0 && data.VT_Tags != nil {
		// If VT tags isn't nil, we ran the passive checks. Just a rough heuristic.
		pdf.SetTextColor(0, 128, 0)
		pdf.SCell(0, 6, "Clean: 0 extracted emails were found in known data breaches.")
		pdf.SetTextColor(0, 0, 0)
		pdf.Ln(8)
	} else {
		pdf.SetTextColor(128, 128, 128)
		pdf.SCell(0, 6, "No credential breaches found or check skipped.")
		pdf.SetTextColor(0, 0, 0)
		pdf.Ln(8)
	}

	// --- Subdomains ---
	pdf.SetFont("Arial", "B", 11)
	pdf.SCell(0, 8, fmt.Sprintf("Stealth Subdomain Enumeration (%d found):", len(data.Subdomains)))
	pdf.Ln(8)
	pdf.SetFont("Arial", "", 9)
	if len(data.Subdomains) > 0 {
		subLimit := 40
		if len(data.Subdomains) < subLimit {
			subLimit = len(data.Subdomains)
		}
		for i := 0; i < subLimit; i++ {
			pdf.SCell(0, 5, "- " + data.Subdomains[i])
			pdf.Ln(5)
		}
		if len(data.Subdomains) > subLimit {
			pdf.SCellFormat(0, 5, fmt.Sprintf("... plus %d more subdomains (see JSON export)", len(data.Subdomains)-subLimit), "", 1, "I", false, 0, "")
		}
	} else {
		pdf.SCell(0, 6, "No subdomains enumerated.")
	}
	pdf.Ln(5)

	// --- Historical & Dorks ---
	pdf.AddPage()
	addSectionHeader(pdf, "7. Historical & External Exposure")
	
	pdf.SetFont("Arial", "B", 11)
	pdf.SCell(0, 8, "Wayback Machine Snapshots")
	pdf.Ln(8)
	pdf.SetFont("Arial", "", 10)
	if len(data.WaybackSnapshots) > 0 {
		for _, snap := range data.WaybackSnapshots {
			pdf.SetTextColor(0, 0, 0)
			pdf.SCell(0, 6, fmt.Sprintf("[%s] Status %s", snap.Timestamp, snap.Status))
			pdf.Ln(6)
			pdf.SetTextColor(0, 0, 255) // Blue link
			pdf.SCellFormat(0, 6, snap.URL, "", 1, "", false, 0, snap.URL)
			pdf.Ln(4)
		}
	} else {
		pdf.SetTextColor(0,0,0)
		pdf.SCell(0, 6, "No Wayback Machine snapshots found.")
		pdf.Ln(8)
	}

	pdf.SetTextColor(0,0,0)
	pdf.Ln(5)
	pdf.SetFont("Arial", "B", 11)
	pdf.SCell(0, 8, "Google Dork Queries")
	pdf.Ln(8)
	pdf.SetFont("Arial", "", 9)
	if len(data.Dorks) > 0 {
		// Only show a few as an example
		limit := 10
		if len(data.Dorks) < limit {
			limit = len(data.Dorks)
		}
		for i := 0; i < limit; i++ {
			dork := data.Dorks[i]
			pdf.SetTextColor(0, 0, 0)
			
			cleanQuery := strings.TrimSpace(strings.TrimPrefix(dork.Query, "Query: "))
			pdf.SCell(0, 5, "Query: " + cleanQuery)
			pdf.Ln(5)
			pdf.SetTextColor(0, 0, 255)
			
			urlPrint := dork.URL
			if len(urlPrint) > 100 {
				urlPrint = urlPrint[:97] + "..."
			}
			pdf.SCellFormat(0, 5, urlPrint, "", 1, "", false, 0, dork.URL)
			pdf.Ln(3)
		}
		pdf.SetTextColor(0,0,0)
		if len(data.Dorks) > limit {
			pdf.SCellFormat(0, 5, fmt.Sprintf("... plus %d more targeted queries (see JSON for full list)", len(data.Dorks)-limit), "", 1, "I", false, 0, "")
		}
	} else {
		pdf.SCell(0, 6, "No standard dorks generated.")
	}

	// Save PDF to file
	outputFile := fmt.Sprintf("%s_report.pdf", data.Domain)
	err := pdf.OutputFileAndClose(outputFile)
	if err != nil {
		return fmt.Errorf("failed to generate PDF report: %v", err)
	}

	log.Printf("PDF report generated successfully: %s", outputFile)
	return nil
}

// addSectionHeader inserts a styled section header
func addSectionHeader(pdf *SafePDF, title string) {
	pdf.SetFont("Arial", "B", 14)
	pdf.SetTextColor(255, 255, 255)
	pdf.SetFillColor(0, 51, 102) // Dark Blue
	pdf.SCellFormat(0, 10, "  " + title, "", 1, "L", true, 0, "")
	pdf.SetTextColor(0, 0, 0) // Reset text color
	pdf.Ln(5)
}
